# Generated by Django 5.0.3 on 2024-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
