# Generated by Django 5.0.3 on 2024-03-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_myuser_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.myuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_image',
            field=models.ImageField(default='default/user.avif', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
