# Generated by Django 5.0.3 on 2024-03-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentpost_author_alter_myuser_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
