# Generated by Django 5.0.3 on 2024-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likepost_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='message',
        ),
        migrations.AddField(
            model_name='commentpost',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
