# Generated by Django 5.0.3 on 2024-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_likepost_message_commentpost_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
