# Generated by Django 5.0.3 on 2024-03-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_likepost_like_count_commentpost_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
